/** Hàm tạo khóa truy vấn theo quy ước trong spec §6.3. */
export const qk = {
  library: ["library"] as const,
  toc: (bookId: string) => ["toc", bookId] as const,
  chapters: (bookId: string) => ["chapters", bookId] as const,
  bookBytes: (bookId: string) => ["book-bytes", bookId] as const,
  progress: (bookId: string) => ["progress", bookId] as const,
  annotations: (bookId: string) => ["annotations", bookId] as const,
  vocabulary: (bookId: string) => ["vocabulary", bookId] as const,
  vocabularyOccurrences: (bookId: string) => ["vocabulary-occurrences", bookId] as const,
  pdfBookmarks: (bookId: string) => ["pdf-bookmarks", bookId] as const,
  bookNotes: (bookId: string) => ["book-notes", bookId] as const,
  book: (bookId: string) => ["book", bookId] as const,
  readingSessions: (bookId: string) => ["reading-sessions", bookId] as const,
  readingSession: (sessionId: string) => ["reading-session", sessionId] as const,
  recentlyRead: ["recently-read"] as const,
  providers: ["providers"] as const,
  conversations: (bookId: string) => ["conversations", bookId] as const,
  messages: (conversationId: string) => ["messages", conversationId] as const,
  stats: (dailyDays: number) => ["stats", dailyDays] as const,
  pageStreak: ["page-streak"] as const,
  memories: ["memories"] as const,
};
