import type { LocalDictionaryEntry, LocalDictionarySense } from "@main/vocabulary/local-dictionary";

/** Independently authored English–Vietnamese glosses for computing, software, and AI/ML. */
type GlossaryRow = readonly [
  term: string,
  domain: string,
  partOfSpeech: string,
  meaning: string,
  example?: string,
  includeGeneralSenses?: boolean,
  contextHints?: readonly string[],
];

export interface TechnicalGlossaryEntry extends LocalDictionaryEntry {
  includeGeneralSenses: boolean;
}

// prettier-ignore
const ROWS: readonly GlossaryRow[] = [
  // Software architecture and NestJS.
  [
    "scalable",
    "Kỹ thuật phần mềm",
    "tính từ",
    "có khả năng mở rộng để xử lý lượng tải tăng lên mà không phải thiết kế lại toàn bộ hệ thống",
    "The service must remain scalable as traffic grows.",
  ],
  [
    "scalability",
    "Kỹ thuật phần mềm",
    "danh từ",
    "khả năng tăng năng lực xử lý của hệ thống khi số người dùng hoặc lượng dữ liệu tăng",
  ],
  [
    "microservice",
    "Kiến trúc phần mềm",
    "danh từ",
    "dịch vụ nhỏ đảm nhiệm một phần chức năng và có thể phát triển, triển khai tương đối độc lập",
    "Each microservice can be deployed independently.",
  ],
  [
    "microservices",
    "Kiến trúc phần mềm",
    "danh từ số nhiều",
    "các dịch vụ nhỏ, tách biệt, phối hợp để tạo thành một ứng dụng",
    "The application is split into microservices.",
  ],
  [
    "microservices",
    "Kiến trúc phần mềm",
    "danh từ",
    "kiến trúc vi dịch vụ: cách xây dựng hệ thống từ nhiều dịch vụ nhỏ giao tiếp qua mạng",
    "The team is migrating to a microservices architecture.",
  ],
  [
    "microservice architecture",
    "Kiến trúc phần mềm",
    "cụm danh từ",
    "kiến trúc chia ứng dụng thành các dịch vụ nhỏ có thể phát triển và triển khai độc lập",
  ],
  [
    "software architecture",
    "Kiến trúc phần mềm",
    "cụm danh từ",
    "cách tổ chức các thành phần của phần mềm và quy định cách chúng giao tiếp với nhau",
  ],
  [
    "software engineering",
    "Kỹ thuật phần mềm",
    "cụm danh từ",
    "ngành áp dụng phương pháp kỹ thuật để thiết kế, phát triển, kiểm thử và bảo trì phần mềm",
  ],
  [
    "distributed system",
    "Hệ thống phân tán",
    "cụm danh từ",
    "hệ thống gồm nhiều máy tính hoặc dịch vụ phối hợp qua mạng nhưng được nhìn như một hệ thống",
  ],
  [
    "monolith",
    "Kiến trúc phần mềm",
    "danh từ",
    "ứng dụng được triển khai như một khối thống nhất, dù bên trong có thể gồm nhiều mô-đun",
  ],
  [
    "modular architecture",
    "Kiến trúc phần mềm",
    "cụm danh từ",
    "cách tổ chức phần mềm thành các mô-đun có trách nhiệm và giao diện tương đối rõ ràng",
  ],
  [
    "NestJS",
    "Kỹ thuật phần mềm",
    "danh từ riêng",
    "framework Node.js dùng TypeScript để xây dựng ứng dụng phía máy chủ theo mô-đun",
  ],
  [
    "Node.js",
    "Kỹ thuật phần mềm",
    "danh từ riêng",
    "môi trường chạy JavaScript ngoài trình duyệt, thường dùng để xây dựng máy chủ và công cụ dòng lệnh",
  ],
  [
    "TypeScript",
    "Kỹ thuật phần mềm",
    "danh từ riêng",
    "ngôn ngữ mở rộng JavaScript với kiểu tĩnh và được biên dịch về JavaScript",
  ],
  ["API", "Kỹ thuật phần mềm", "viết tắt", "giao diện quy định cách phần mềm khác yêu cầu và nhận dữ liệu hoặc chức năng"],
  ["REST", "Kỹ thuật phần mềm", "viết tắt", "kiểu thiết kế API web dựa trên tài nguyên, URI và các phương thức HTTP"],
  ["REST API", "Kỹ thuật phần mềm", "cụm danh từ", "API web biểu diễn tài nguyên bằng URI và dùng các phương thức HTTP để thao tác"],
  ["GraphQL", "Kỹ thuật phần mềm", "danh từ riêng", "ngôn ngữ truy vấn API cho phép client yêu cầu đúng các trường dữ liệu cần dùng"],
  ["GraphQL resolver", "Kỹ thuật phần mềm", "cụm danh từ", "hàm lấy hoặc tính giá trị cho một trường trong kết quả GraphQL"],
  ["resolver", "Kỹ thuật phần mềm", "danh từ", "hàm giải quyết một trường hoặc truy vấn bằng cách cung cấp giá trị kết quả"],
  ["endpoint", "Kỹ thuật phần mềm", "danh từ", "địa chỉ hoặc điểm truy cập cụ thể mà client dùng để gọi một API"],
  ["route", "Kỹ thuật phần mềm", "danh từ", "quy tắc ánh xạ đường dẫn và phương thức HTTP tới bộ xử lý tương ứng"],
  ["controller", "Kỹ thuật phần mềm", "danh từ", "thành phần nhận request, chọn thao tác cần thực hiện và chuyển công việc cho lớp khác"],
  [
    "provider",
    "Kỹ thuật phần mềm",
    "danh từ",
    "đối tượng hoặc lớp mà container của NestJS có thể khởi tạo và tiêm vào thành phần khác",
    "The controller receives the service provider through its constructor.",
    false,
    ["NestJS", "dependency injection", "provider class", "constructor", "inject", "container"],
  ],
  [
    "provider",
    "Tích hợp hệ thống",
    "danh từ",
    "dịch vụ bên ngoài cung cấp API hoặc gửi sự kiện webhook cho ứng dụng",
    "The webhook provider sends payment events to the application.",
    true,
    ["webhook", "Stripe", "inbound webhook", "provider behavior", "external provider", "third-party"],
  ],
  ["module", "Kỹ thuật phần mềm", "danh từ", "đơn vị tổ chức các thành phần và quan hệ phụ thuộc trong một ứng dụng" , undefined, true],
  ["module", "Kỹ thuật phần mềm", "danh từ", "đơn vị mã có thể được nhập, xuất hoặc tái sử dụng trong một chương trình", undefined, true],
  [
    "dependency injection",
    "Kỹ thuật phần mềm",
    "cụm danh từ",
    "cách cung cấp dependency từ bên ngoài cho đối tượng thay vì để đối tượng tự tạo chúng",
    "NestJS resolves the service through dependency injection.",
  ],
  ["middleware", "Kỹ thuật phần mềm", "danh từ", "thành phần trung gian xử lý request trước khi request tới handler cuối cùng"],
  ["guard", "Kỹ thuật phần mềm", "danh từ", "thành phần quyết định request có được phép đi tiếp hay không, thường dựa trên quyền truy cập"],
  ["interceptor", "Kỹ thuật phần mềm", "danh từ", "thành phần có thể chạy logic trước và sau handler để biến đổi hoặc quan sát kết quả"],
  ["pipe", "Kỹ thuật phần mềm", "danh từ", "thành phần biến đổi hoặc kiểm tra dữ liệu đầu vào trước khi gọi handler"],
  ["decorator", "Kỹ thuật phần mềm", "danh từ", "cú pháp gắn metadata hoặc hành vi bổ sung lên lớp, phương thức hay thuộc tính"],
  ["gateway", "Kỹ thuật phần mềm", "danh từ", "thành phần làm điểm kết nối giữa client hoặc hệ thống với một nhóm dịch vụ phía sau"],
  ["transport layer", "Mạng máy tính", "cụm danh từ", "lớp hoặc cơ chế chuyển dữ liệu giữa các tiến trình hoặc dịch vụ qua mạng"],
  ["message broker", "Hệ thống phân tán", "cụm danh từ", "phần mềm trung gian nhận, định tuyến và chuyển thông điệp giữa các hệ thống"],
  ["message queue", "Hệ thống phân tán", "cụm danh từ", "hàng đợi lưu thông điệp để bên gửi và bên nhận xử lý lệch thời điểm"],
  ["request-response", "Hệ thống phân tán", "cụm danh từ", "mẫu giao tiếp trong đó bên gửi yêu cầu và chờ bên nhận trả lời"],
  ["event pattern", "Kỹ thuật phần mềm", "cụm danh từ", "mẫu giao tiếp trong đó bên phát công bố sự kiện và không cần chờ phản hồi trực tiếp"],
  ["message pattern", "Kỹ thuật phần mềm", "cụm danh từ", "mẫu quy định cấu trúc và cách trao đổi thông điệp giữa các thành phần"],
  ["client", "Kỹ thuật phần mềm", "danh từ", "chương trình hoặc thành phần gửi yêu cầu tới một dịch vụ khác", undefined, true],
  ["server", "Kỹ thuật phần mềm", "danh từ", "chương trình hoặc máy tính nhận yêu cầu và cung cấp dữ liệu hay chức năng", undefined, true],
  ["service", "Kiến trúc phần mềm", "danh từ", "thành phần cung cấp một chức năng có thể được gọi qua giao diện xác định", undefined, true],
  ["service", "Kiến trúc phần mềm", "danh từ", "ứng dụng phía máy chủ cung cấp một chức năng riêng qua mạng", undefined, true],
  ["API gateway", "Kiến trúc phần mềm", "cụm danh từ", "điểm vào nhận request từ client rồi định tuyến hoặc áp dụng chính sách trước khi chuyển tới dịch vụ"],
  ["service discovery", "Hệ thống phân tán", "cụm danh từ", "cơ chế để dịch vụ tìm địa chỉ các dịch vụ khác đang hoạt động"],
  ["synchronous", "Kỹ thuật phần mềm", "tính từ", "diễn ra theo cách bên gọi phải chờ thao tác hiện tại hoàn tất trước khi tiếp tục"],
  ["asynchronous", "Kỹ thuật phần mềm", "tính từ", "diễn ra theo cách bên gọi có thể tiếp tục làm việc trong khi thao tác khác chưa hoàn tất"],
  ["event-driven architecture", "Kiến trúc phần mềm", "cụm danh từ", "kiến trúc trong đó các thành phần phát và phản ứng với sự kiện thay vì gọi nhau trực tiếp"],
  // Distributed systems, scaling, operations, and performance.
  ["throughput", "Hệ thống phân tán", "danh từ", "lượng request, dữ liệu hoặc công việc hệ thống xử lý được trong một đơn vị thời gian"],
  [
    "performance",
    "Hiệu năng hệ thống",
    "danh từ",
    "tốc độ xử lý và khả năng phản hồi của hệ thống khi hoạt động dưới tải",
    "Application performance improved after reducing database latency.",
    true,
    [
      "application performance",
      "system performance",
      "database performance",
      "website performance",
      "performance bottleneck",
      "performance degrades",
      "performance degradation",
      "high performance",
      "load",
      "latency",
      "throughput",
      "response time",
      "slow",
      "scalability",
      "benchmark",
    ],
  ],
  ["latency", "Hệ thống phân tán", "danh từ", "thời gian chờ từ lúc gửi yêu cầu đến khi nhận được phản hồi"],
  ["load balancer", "Hệ thống phân tán", "cụm danh từ", "thành phần phân phối request tới nhiều máy chủ hoặc bản sao dịch vụ"],
  ["load balancing", "Hệ thống phân tán", "cụm danh từ", "việc phân phối tải giữa nhiều máy chủ để tránh một máy bị quá tải"],
  ["horizontal scaling", "Hệ thống phân tán", "cụm danh từ", "tăng năng lực bằng cách thêm máy chủ hoặc bản sao dịch vụ"],
  ["vertical scaling", "Hệ thống phân tán", "cụm danh từ", "tăng năng lực bằng cách nâng CPU, bộ nhớ hoặc tài nguyên của một máy chủ"],
  ["availability", "Hệ thống phân tán", "danh từ", "mức độ hệ thống sẵn sàng phục vụ khi người dùng cần"],
  ["high availability", "Hệ thống phân tán", "cụm danh từ", "thiết kế nhằm giữ dịch vụ hoạt động với thời gian gián đoạn thấp"],
  ["reliability", "Hệ thống phân tán", "danh từ", "khả năng hệ thống hoạt động đúng và ổn định trong khoảng thời gian dự kiến"],
  ["resilience", "Hệ thống phân tán", "danh từ", "khả năng tiếp tục cung cấp chức năng hoặc phục hồi sau lỗi"],
  ["fault tolerance", "Hệ thống phân tán", "cụm danh từ", "khả năng tiếp tục hoạt động dù một số thành phần gặp lỗi"],
  ["failover", "Hệ thống phân tán", "danh từ", "chuyển tự động sang máy chủ hoặc thành phần dự phòng khi thành phần chính lỗi"],
  ["circuit breaker", "Hệ thống phân tán", "cụm danh từ", "cơ chế tạm ngừng gọi dịch vụ đang lỗi để tránh lỗi lan rộng"],
  ["idempotent", "Kỹ thuật phần mềm", "tính từ", "có kết quả cuối như nhau khi cùng một thao tác được thực hiện một lần hoặc nhiều lần"],
  ["idempotency", "Kỹ thuật phần mềm", "danh từ", "tính chất giúp lặp lại thao tác mà không tạo thêm tác động ngoài dự kiến"],
  ["retry", "Kỹ thuật phần mềm", "danh từ/động từ", "thử thực hiện lại thao tác sau khi thao tác trước thất bại"],
  ["exponential backoff", "Hệ thống phân tán", "cụm danh từ", "cách tăng dần thời gian chờ giữa các lần thử lại theo cấp số nhân"],
  ["cache", "Kỹ thuật phần mềm", "danh từ", "nơi lưu tạm dữ liệu thường dùng để giảm thời gian lấy lại từ nguồn chậm hơn", undefined, true],
  ["caching", "Kỹ thuật phần mềm", "danh từ", "kỹ thuật lưu tạm dữ liệu để những lần truy cập sau nhanh hơn"],
  ["cache invalidation", "Kỹ thuật phần mềm", "cụm danh từ", "việc đánh dấu hoặc xóa dữ liệu cache đã cũ để tránh dùng kết quả lỗi thời"],
  ["container", "DevOps & hạ tầng", "danh từ", "môi trường chạy cô lập gói ứng dụng cùng các phụ thuộc cần thiết"],
  ["containerization", "DevOps & hạ tầng", "danh từ", "cách đóng gói ứng dụng và phụ thuộc trong container để chạy nhất quán"],
  [
    "orchestration",
    "DevOps & hạ tầng",
    "danh từ",
    "tự động triển khai, kết nối, mở rộng và phục hồi nhiều container hoặc dịch vụ",
    undefined,
    false,
    ["container orchestration", "Kubernetes", "pod", "container", "scale", "deployment"],
  ],
  [
    "orchestration",
    "Hệ thống phân tán",
    "danh từ",
    "cách điều phối thứ tự các bước nghiệp vụ hoặc dịch vụ, theo dõi kết quả và kích hoạt hành động bù khi một bước thất bại",
    "The Saga orchestrator calls each service and dispatches compensations on failure.",
    false,
    ["Saga", "workflow", "compensating", "central orchestrator", "state machine", "dispatches compensations"],
  ],
  ["deployment", "DevOps & hạ tầng", "danh từ", "quá trình đưa phiên bản phần mềm lên môi trường để người dùng hoặc hệ thống sử dụng"],
  ["Docker", "DevOps & hạ tầng", "danh từ riêng", "nền tảng thường dùng để đóng gói và chạy ứng dụng trong container"],
  ["Kubernetes", "DevOps & hạ tầng", "danh từ riêng", "hệ thống điều phối việc triển khai và vận hành ứng dụng dạng container"],
  ["health check", "DevOps & hạ tầng", "cụm danh từ", "kiểm tra định kỳ để xác định dịch vụ hoặc thành phần còn hoạt động bình thường"],
  ["observability", "DevOps & hạ tầng", "danh từ", "khả năng suy ra trạng thái bên trong hệ thống từ log, metric và trace"],
  ["monitoring", "DevOps & hạ tầng", "danh từ", "việc theo dõi trạng thái và chỉ số của hệ thống để phát hiện vấn đề"],
  ["logging", "DevOps & hạ tầng", "danh từ", "việc ghi lại sự kiện và thông tin phục vụ vận hành hoặc tìm lỗi"],
  ["tracing", "DevOps & hạ tầng", "danh từ", "cách theo dấu một request qua nhiều thành phần trong hệ thống"],
  ["metrics", "DevOps & hạ tầng", "danh từ số nhiều", "các số đo tổng hợp như độ trễ, số lỗi hoặc mức sử dụng tài nguyên"],
  ["telemetry", "DevOps & hạ tầng", "danh từ", "dữ liệu tự động thu thập về hoạt động và hiệu năng của phần mềm"],
  // Computer science foundations.
  [
    "programming",
    "Khoa học máy tính",
    "danh từ",
    "hoạt động thiết kế, viết, kiểm thử và duy trì chương trình máy tính",
    "Programming requires careful testing.",
    false,
    ["software development", "writing code", "computer program", "programmer", "source code"],
  ],
  [
    "pointer",
    "Khoa học máy tính",
    "danh từ",
    "biến hoặc giá trị chứa địa chỉ của một đối tượng trong bộ nhớ để chương trình có thể truy cập đối tượng đó",
    "The function returns a pointer to the first element.",
    false,
    ["memory address", "pointer arithmetic", "dereference", "c pointer", "memory allocation"],
  ],
  [
    "pointer",
    "Kỹ thuật phần mềm",
    "danh từ",
    "tham chiếu chỉ tới vị trí hoặc phiên bản dữ liệu hiện hành, chẳng hạn bảng đang được dùng để đọc sau khi chuyển đổi schema",
    "Flip the read pointer to the new table after migration.",
    false,
    ["read pointer", "flip the read pointer", "users_v2 table", "schema migration", "migration"],
  ],
  [
    "kernel",
    "Hệ điều hành",
    "danh từ",
    "phần lõi của hệ điều hành, quản lý tài nguyên và làm trung gian giữa phần cứng với chương trình",
    "The kernel manages access to system resources.",
    false,
    ["operating system", "system call", "device driver", "kernel mode", "process scheduler"],
  ],
  [
    "kernel",
    "AI/ML",
    "danh từ",
    "hàm đo mức độ tương tự giữa các điểm dữ liệu, được dùng trong một số thuật toán học máy như SVM",
    "The classifier uses a radial basis function kernel.",
    false,
    ["support vector machine", "svm", "kernel function", "feature space", "radial basis"],
  ],
  [
    "kernel",
    "GPU & Hệ thống",
    "danh từ",
    "hàm hoặc chương trình nhỏ được GPU chạy song song trên nhiều phần tử dữ liệu",
    "The GPU launches a kernel to process the input batch.",
    false,
    ["GPU", "GPU kernel", "kernel launch", "CUDA", "thread block", "GPU kernel launch overhead"],
  ],
  ["algorithm", "Khoa học máy tính", "danh từ", "tập hợp hữu hạn các bước xác định để giải quyết một bài toán"],
  ["data structure", "Khoa học máy tính", "cụm danh từ", "cách tổ chức dữ liệu để truy cập hoặc cập nhật hiệu quả"],
  ["time complexity", "Khoa học máy tính", "cụm danh từ", "mức tăng thời gian chạy của thuật toán khi kích thước đầu vào tăng"],
  ["space complexity", "Khoa học máy tính", "cụm danh từ", "mức tăng bộ nhớ thuật toán cần dùng khi kích thước đầu vào tăng"],
  ["Big O notation", "Khoa học máy tính", "cụm danh từ", "ký hiệu mô tả tốc độ tăng tiệm cận của thời gian hoặc bộ nhớ theo kích thước đầu vào"],
  ["recursion", "Khoa học máy tính", "danh từ", "cách giải bài toán bằng việc hàm gọi lại chính nó cho bài toán con nhỏ hơn"],
  ["hash table", "Khoa học máy tính", "cụm danh từ", "cấu trúc ánh xạ khóa tới giá trị bằng hàm băm"],
  ["linked list", "Khoa học máy tính", "cụm danh từ", "cấu trúc gồm các nút, mỗi nút liên kết tới nút kế tiếp hoặc nút lân cận"],
  ["stack", "Khoa học máy tính", "danh từ", "cấu trúc dữ liệu vào sau ra trước"],
  ["queue", "Khoa học máy tính", "danh từ", "cấu trúc dữ liệu thường xử lý phần tử theo thứ tự vào trước ra trước", undefined, true],
  ["queue", "Hệ thống phân tán", "danh từ", "hàng đợi lưu công việc hoặc thông điệp chờ được xử lý", undefined, true],
  ["tree", "Khoa học máy tính", "danh từ", "cấu trúc dữ liệu phân cấp gồm nút gốc và các nút con"],
  ["graph", "Khoa học máy tính", "danh từ", "cấu trúc gồm các đỉnh và cạnh mô tả quan hệ giữa chúng"],
  ["concurrency", "Khoa học máy tính", "danh từ", "cách nhiều tác vụ cùng tiến triển trong một khoảng thời gian, dù không nhất thiết chạy đồng thời"],
  ["parallelism", "Khoa học máy tính", "danh từ", "việc thực thi nhiều tác vụ thật sự cùng lúc trên nhiều đơn vị xử lý"],
  ["process", "Khoa học máy tính", "danh từ", "chương trình đang chạy cùng trạng thái và tài nguyên riêng", undefined, true],
  ["process", "Kỹ thuật phần mềm", "danh từ", "chuỗi bước được quy định để thực hiện một công việc", undefined, true],
  ["thread", "Khoa học máy tính", "danh từ", "luồng thực thi bên trong một tiến trình, có thể chia sẻ tài nguyên với luồng khác"],
  ["event loop", "Khoa học máy tính", "cụm danh từ", "cơ chế nhận và phân phối sự kiện hoặc callback để chương trình xử lý lần lượt"],
  ["race condition", "Khoa học máy tính", "cụm danh từ", "lỗi xảy ra khi kết quả phụ thuộc vào thứ tự không ổn định của các tác vụ đồng thời"],
  ["deadlock", "Khoa học máy tính", "danh từ", "trạng thái các tác vụ chờ tài nguyên của nhau nên không tác vụ nào tiếp tục được"],
  ["mutex", "Khoa học máy tính", "danh từ", "khóa loại trừ tương hỗ bảo đảm chỉ một luồng truy cập vùng tài nguyên tại một thời điểm"],
  ["semaphore", "Khoa học máy tính", "danh từ", "cơ chế đồng bộ giới hạn số tác vụ cùng truy cập một tài nguyên"],
  ["runtime", "Khoa học máy tính", "danh từ", "môi trường và thời gian một chương trình đang được thực thi"],
  ["compiler", "Khoa học máy tính", "danh từ", "chương trình chuyển mã nguồn sang dạng khác, thường để chạy hoặc tối ưu"],
  ["interpreter", "Khoa học máy tính", "danh từ", "chương trình đọc và thực thi mã nguồn hoặc dạng trung gian khi chạy"],
  ["protocol", "Mạng máy tính", "danh từ", "tập quy tắc xác định cách các thiết bị hoặc chương trình trao đổi dữ liệu"],
  [
    "traffic",
    "Mạng máy tính",
    "danh từ",
    "lượng yêu cầu hoặc dữ liệu đi qua mạng hay một dịch vụ trong một khoảng thời gian",
    "The load balancer distributes traffic across the service instances.",
    true,
    ["load balancer", "request traffic", "traffic spike", "RPS", "requests per second", "network traffic"],
  ],
  ["socket", "Mạng máy tính", "danh từ", "đầu cuối giao tiếp mà chương trình dùng để gửi và nhận dữ liệu qua mạng"],
  ["buffer", "Khoa học máy tính", "danh từ", "vùng nhớ tạm giữ dữ liệu khi dữ liệu được chuyển hoặc xử lý"],
  ["stream", "Khoa học máy tính", "danh từ", "luồng dữ liệu được đọc hoặc ghi dần thay vì nạp toàn bộ cùng lúc", undefined, true],
  [
    "serialization",
    "Khoa học máy tính",
    "danh từ",
    "chuyển đối tượng hoặc cấu trúc dữ liệu thành dạng có thể lưu trữ hoặc truyền đi",
    undefined,
    false,
    ["serialize object", "serialized data", "JSON", "wire format", "store or transmit"],
  ],
  [
    "serialization",
    "Cơ sở dữ liệu",
    "danh từ",
    "tính chất các giao dịch đồng thời có thể được sắp xếp thành một thứ tự thực thi nối tiếp tương đương; lỗi tuần tự hóa khiến giao dịch phải hủy và thử lại",
    "PostgreSQL can abort and retry a transaction after a serialization failure.",
    false,
    ["serializable isolation", "serialization failure", "serialization failures", "PostgreSQL SSI", "transaction abort", "concurrent transaction"],
  ],
  ["deserialization", "Khoa học máy tính", "danh từ", "khôi phục cấu trúc dữ liệu từ dạng đã được tuần tự hóa"],
  ["encoding", "Khoa học máy tính", "danh từ", "quy tắc biểu diễn dữ liệu bằng một dạng ký hiệu hoặc byte cụ thể"],
  ["parser", "Khoa học máy tính", "danh từ", "chương trình phân tích cấu trúc dữ liệu hoặc mã theo một ngữ pháp"],
  ["parsing", "Khoa học máy tính", "danh từ", "quá trình phân tích chuỗi dữ liệu để nhận ra cấu trúc và thành phần"],
  ["memory leak", "Khoa học máy tính", "cụm danh từ", "tình trạng chương trình giữ lại bộ nhớ không còn cần dùng khiến mức sử dụng tăng dần"],
  [
    "memory",
    "Hệ thống máy tính",
    "danh từ",
    "bộ nhớ của máy tính dùng để lưu dữ liệu và lệnh khi chương trình hoặc bộ xử lý đang hoạt động",
    "The limiter uses O(1) memory per key.",
    true,
    ["O(1) memory", "memory per key", "GPU memory", "memory footprint", "RAM", "heap", "bytes"],
  ],
  ["garbage collection", "Khoa học máy tính", "cụm danh từ", "cơ chế tự thu hồi bộ nhớ của các đối tượng không còn được sử dụng"],
  // Databases and software quality.
  ["database", "Cơ sở dữ liệu", "danh từ", "tập dữ liệu được tổ chức để có thể truy vấn, cập nhật và quản lý", undefined, true],
  ["relational database", "Cơ sở dữ liệu", "cụm danh từ", "cơ sở dữ liệu lưu dữ liệu trong các bảng có quan hệ với nhau"],
  ["NoSQL database", "Cơ sở dữ liệu", "cụm danh từ", "cơ sở dữ liệu không bắt buộc mô hình bảng quan hệ cố định"],
  [
    "query",
    "Cơ sở dữ liệu",
    "danh từ",
    "yêu cầu đọc, thêm, sửa hoặc xóa dữ liệu trong cơ sở dữ liệu, thường được mô tả bằng câu lệnh như SQL",
    "The query log shows one database query for each order.",
    true,
    ["query log", "N+1", "SQL", "SELECT", "database query", "DynamoDB", "query pattern"],
  ],
  [
    "partition",
    "Cơ sở dữ liệu",
    "danh từ",
    "phần dữ liệu được chia từ một bảng, chủ đề hoặc tập dữ liệu lớn để lưu trữ và xử lý riêng",
    "Kafka routes events with the same partition key to the same partition.",
    true,
    ["partition key", "Kafka", "DynamoDB", "sharding", "table partition", "partitioned data"],
  ],
  [
    "consistency",
    "Cơ sở dữ liệu",
    "danh từ",
    "mức bảo đảm các lần đọc và các bản sao phản ánh dữ liệu đã ghi theo quy tắc nhất quán của hệ thống",
    "The read store has eventual consistency with the primary database.",
    true,
    ["eventual consistency", "read store", "read replicas", "replica", "primary database", "read-your-writes"],
  ],
  [
    "index",
    "Cơ sở dữ liệu",
    "danh từ",
    "cấu trúc phụ trợ cho phép cơ sở dữ liệu tìm bản ghi theo trường nhanh hơn mà không phải quét toàn bộ bảng",
    "A B-tree index speeds up the lookup but adds write cost.",
    true,
    ["B-tree", "index scan", "Elasticsearch index", "Postgres index", "database index", "table scan", "query plan"],
  ],
  ["schema", "Cơ sở dữ liệu", "danh từ", "mô tả cấu trúc dữ liệu, trường, kiểu và các ràng buộc của dữ liệu", undefined, true],
  ["ORM", "Cơ sở dữ liệu", "viết tắt", "kỹ thuật ánh xạ đối tượng trong chương trình sang bảng hoặc bản ghi cơ sở dữ liệu"],
  ["object-relational mapping", "Cơ sở dữ liệu", "cụm danh từ", "kỹ thuật ánh xạ đối tượng trong mã nguồn với cấu trúc của cơ sở dữ liệu quan hệ"],
  ["transaction", "Cơ sở dữ liệu", "danh từ", "nhóm thao tác được xử lý như một đơn vị để bảo đảm trạng thái dữ liệu nhất quán"],
  ["ACID", "Cơ sở dữ liệu", "viết tắt", "bốn thuộc tính giao dịch: tính nguyên tử, nhất quán, cô lập và bền vững"],
  ["database migration", "Cơ sở dữ liệu", "cụm danh từ", "thay đổi có kiểm soát đối với cấu trúc hoặc dữ liệu của cơ sở dữ liệu"],
  ["replication", "Cơ sở dữ liệu", "danh từ", "việc duy trì bản sao dữ liệu trên nhiều máy hoặc nút"],
  ["sharding", "Cơ sở dữ liệu", "danh từ", "chia dữ liệu thành các phần và phân bố chúng trên nhiều máy hoặc nút"],
  ["partitioning", "Cơ sở dữ liệu", "danh từ", "chia bảng hoặc tập dữ liệu lớn thành các phần nhỏ hơn để quản lý và truy cập"],
  ["database index", "Cơ sở dữ liệu", "cụm danh từ", "cấu trúc phụ giúp tìm bản ghi nhanh hơn, thường đổi lại chi phí lưu trữ và cập nhật"],
  ["database query", "Cơ sở dữ liệu", "cụm danh từ", "yêu cầu dùng để đọc, thêm, sửa hoặc xóa dữ liệu trong cơ sở dữ liệu"],
  ["eventual consistency", "Cơ sở dữ liệu", "cụm danh từ", "mô hình trong đó các bản sao có thể tạm thời khác nhau nhưng sẽ hội tụ nếu không có cập nhật mới"],
  ["CAP theorem", "Cơ sở dữ liệu", "cụm danh từ", "mệnh đề về sự đánh đổi giữa tính nhất quán, tính sẵn sàng và khả năng chịu phân vùng mạng"],
  ["unit testing", "Kiểm thử phần mềm", "cụm danh từ", "kiểm thử một hàm hoặc đơn vị nhỏ độc lập với phần còn lại của hệ thống"],
  ["integration testing", "Kiểm thử phần mềm", "cụm danh từ", "kiểm thử cách nhiều mô-đun hoặc dịch vụ phối hợp với nhau"],
  ["end-to-end testing", "Kiểm thử phần mềm", "cụm danh từ", "kiểm thử một luồng hoàn chỉnh từ điểm vào đến kết quả cuối như người dùng trải nghiệm"],
  ["regression testing", "Kiểm thử phần mềm", "cụm danh từ", "chạy lại các kiểm thử để phát hiện lỗi mới do thay đổi gần đây gây ra"],
  ["mock", "Kiểm thử phần mềm", "danh từ", "đối tượng giả lập dependency để kiểm thử hành vi của thành phần đang xét"],
  ["stub", "Kiểm thử phần mềm", "danh từ", "thành phần thay thế tối giản trả về kết quả định trước trong kiểm thử"],
  ["fixture", "Kiểm thử phần mềm", "danh từ", "dữ liệu hoặc trạng thái chuẩn bị sẵn để dùng trong một hay nhiều kiểm thử"],
  ["test coverage", "Kiểm thử phần mềm", "cụm danh từ", "tỷ lệ mã hoặc nhánh chương trình được thực thi trong các kiểm thử"],
  // Delivery, security, and operations.
  ["continuous integration", "DevOps & hạ tầng", "cụm danh từ", "thực hành hợp nhất thay đổi mã thường xuyên và tự động kiểm tra chúng"],
  ["continuous delivery", "DevOps & hạ tầng", "cụm danh từ", "quy trình tự động giữ phần mềm ở trạng thái có thể phát hành"],
  ["CI/CD", "DevOps & hạ tầng", "viết tắt", "tự động hóa tích hợp thay đổi và các bước đưa phần mềm tới môi trường phát hành"],
  [
    "pipeline",
    "DevOps & hạ tầng",
    "danh từ",
    "chuỗi bước tự động xử lý mã, kiểm thử hoặc phát hành phần mềm",
    undefined,
    false,
    ["CI/CD", "continuous integration", "continuous delivery", "build pipeline", "release pipeline", "code pipeline"],
  ],
  [
    "pipeline",
    "Khoa học dữ liệu",
    "danh từ",
    "chuỗi bước thu thập, biến đổi và chuyển dữ liệu giữa nguồn, quá trình xử lý và kho đích",
    "The analytics pipeline processes events from each tenant.",
    false,
    ["analytics pipeline", "data pipeline", "data ingestion", "event stream", "multi-tenant analytics", "data transformation"],
  ],
  ["version control", "Kỹ thuật phần mềm", "cụm danh từ", "hệ thống ghi lại lịch sử thay đổi và hỗ trợ cộng tác trên mã nguồn"],
  ["rollback", "DevOps & hạ tầng", "danh từ/động từ", "hoàn tác thay đổi hoặc quay về phiên bản trước khi phát sinh sự cố"],
  ["release", "Kỹ thuật phần mềm", "danh từ", "phiên bản phần mềm được công bố để người khác cài đặt hoặc sử dụng"],
  ["environment variable", "DevOps & hạ tầng", "cụm danh từ", "giá trị cấu hình được cung cấp cho tiến trình từ môi trường chạy"],
  ["configuration", "Kỹ thuật phần mềm", "danh từ", "các giá trị điều khiển cách chương trình hoạt động mà không phải sửa logic chính"],
  ["authentication", "Bảo mật", "danh từ", "quá trình xác minh người dùng hoặc hệ thống là chủ thể nào"],
  ["authorization", "Bảo mật", "danh từ", "quá trình xác định chủ thể đã xác thực được phép thực hiện thao tác nào"],
  ["access control", "Bảo mật", "cụm danh từ", "các quy tắc giới hạn ai hoặc thành phần nào được truy cập tài nguyên"],
  ["rate limiting", "Bảo mật", "cụm danh từ", "giới hạn số request được chấp nhận trong một khoảng thời gian"],
  ["input validation", "Bảo mật", "cụm danh từ", "kiểm tra dữ liệu đầu vào có đúng định dạng và ràng buộc mong đợi hay không"],
  ["SQL injection", "Bảo mật", "cụm danh từ", "lỗ hổng cho phép dữ liệu đầu vào làm thay đổi ngoài ý muốn câu lệnh SQL"],
  ["cross-site scripting", "Bảo mật", "cụm danh từ", "lỗ hổng cho phép mã script không tin cậy chạy trong trình duyệt của người dùng"],
  ["CORS", "Bảo mật web", "viết tắt", "cơ chế trình duyệt kiểm soát request giữa các origin khác nhau"],
  ["TLS", "Bảo mật mạng", "viết tắt", "giao thức mã hóa và xác thực kết nối giữa hai đầu giao tiếp"],
  [
    "token",
    "Bảo mật",
    "danh từ",
    "chuỗi dữ liệu dùng để đại diện quyền hoặc phiên xác thực",
    undefined,
    true,
    ["authorization", "access token", "authentication", "JWT", "OAuth", "session token", "bearer token"],
  ],
  [
    "token",
    "AI/ML",
    "danh từ",
    "đơn vị văn bản mà mô hình ngôn ngữ xử lý, có thể là từ, một phần từ hoặc ký hiệu",
    undefined,
    true,
    ["language model", "tokenizer", "text token", "model input", "LLM", "vocabulary"],
  ],
  [
    "token",
    "Mạng máy tính",
    "danh từ",
    "đơn vị quyền xử lý được nạp vào bucket của bộ giới hạn tốc độ; mỗi yêu cầu tiêu thụ một token và bucket được nạp lại theo tốc độ cấu hình",
    "Each request consumes a token from the rate limiter's bucket.",
    true,
    ["token bucket", "leaky bucket", "rate limit", "rate limiter", "refill", "requests per second"],
  ],
  ["JWT", "Bảo mật", "viết tắt", "định dạng token chứa các claim được mã hóa hoặc ký để truyền giữa các bên"],
  ["OAuth", "Bảo mật", "danh từ riêng", "chuẩn ủy quyền cho phép ứng dụng truy cập tài nguyên theo quyền được cấp"],
  ["secret management", "Bảo mật", "cụm danh từ", "cách lưu, cấp phát, xoay vòng và bảo vệ khóa hoặc thông tin xác thực"],
  [
    "data masking",
    "Bảo mật dữ liệu",
    "cụm danh từ",
    "kỹ thuật che hoặc thay thế dữ liệu nhạy cảm khi hiển thị hay dùng bản sao để giảm nguy cơ lộ thông tin",
    "Data masking hides sensitive values in reports.",
    false,
    ["sensitive data", "privacy", "personally identifiable", "pii", "data masking", "application security"],
  ],
  [
    "tokenization",
    "Bảo mật dữ liệu",
    "danh từ",
    "thay dữ liệu nhạy cảm bằng mã đại diện không mang ý nghĩa bên ngoài hệ thống ánh xạ token",
    "Tokenization replaces card numbers with surrogate tokens.",
    false,
    ["sensitive data", "data masking", "payment card", "card number", "token vault", "application security"],
  ],
  // Artificial intelligence and machine learning.
  ["artificial intelligence", "AI/ML", "cụm danh từ", "lĩnh vực tạo hệ thống có thể thực hiện tác vụ thường cần năng lực trí tuệ của con người"],
  ["machine learning", "Khoa học máy tính · AI/ML", "cụm danh từ", "phương pháp để chương trình học quy luật từ dữ liệu nhằm dự đoán hoặc ra quyết định"],
  ["deep learning", "AI/ML", "cụm danh từ", "nhánh máy học dùng mạng nơ-ron nhiều lớp để học biểu diễn từ dữ liệu"],
  ["neural network", "AI/ML", "cụm danh từ", "mô hình tính toán gồm các nút liên kết, thường được huấn luyện từ dữ liệu"],
  [
    "model",
    "AI/ML",
    "danh từ",
    "hàm đã được huấn luyện để biến đầu vào thành dự đoán hoặc kết quả",
    undefined,
    true,
    ["trained model", "prediction", "model inference", "model weights", "machine learning model", "AI feature"],
  ],
  [
    "model",
    "Kỹ thuật phần mềm",
    "danh từ",
    "biểu diễn đơn giản hóa một miền nghiệp vụ, dữ liệu hoặc hệ thống",
    undefined,
    true,
    ["read model", "write model", "read side", "write side", "data model", "domain model", "model boundaries"],
  ],
  ["training", "AI/ML", "danh từ", "quá trình điều chỉnh tham số mô hình dựa trên dữ liệu và mục tiêu đã chọn"],
  ["inference", "AI/ML", "danh từ", "quá trình dùng mô hình đã huấn luyện để tạo dự đoán từ đầu vào mới"],
  ["dataset", "AI/ML", "danh từ", "tập hợp các mẫu dữ liệu dùng để huấn luyện, đánh giá hoặc sử dụng mô hình"],
  [
    "feature",
    "AI/ML",
    "danh từ",
    "thuộc tính đầu vào được dùng để mô tả một mẫu dữ liệu cho mô hình",
    undefined,
    true,
    ["feature vector", "training data", "model input", "classification", "input feature"],
  ],
  [
    "feature",
    "Kỹ thuật phần mềm",
    "danh từ",
    "chức năng hoặc khả năng cụ thể mà sản phẩm phần mềm cung cấp",
    undefined,
    true,
    ["product feature", "software feature", "product capability", "application feature"],
  ],
  [
    "feature",
    "Kỹ thuật phần mềm",
    "danh từ",
    "công tắc cấu hình dùng để bật hoặc tắt chức năng, thường triển khai trước rồi mở dần cho người dùng",
    "A feature flag keeps the new capability disabled until rollout.",
    true,
    ["feature flag", "flag defaulting", "behind a flag", "rollout", "toggle", "flag is off"],
  ],
  ["label", "AI/ML", "danh từ", "nhãn hoặc kết quả đúng gắn với một mẫu dữ liệu để huấn luyện hay đánh giá"],
  ["classification", "AI/ML", "danh từ", "bài toán gán một mẫu đầu vào vào một hay nhiều nhóm đã xác định"],
  ["regression", "AI/ML", "danh từ", "bài toán dự đoán một giá trị số liên tục từ đầu vào"],
  ["embedding", "AI/ML", "danh từ", "biểu diễn dữ liệu thành vector số để so sánh hoặc xử lý ngữ nghĩa"],
  [
    "tokenization",
    "AI/ML",
    "danh từ",
    "quá trình chia văn bản thành token theo quy tắc của bộ tokenizer để mô hình hoặc bộ xử lý ngôn ngữ sử dụng",
    "Tokenization splits a sentence into tokens for processing.",
    false,
    ["language model", "tokenizer", "natural language processing", "nlp", "machine learning", "text processing"],
  ],
  ["transformer", "AI/ML", "danh từ", "kiến trúc mạng nơ-ron dùng attention để xử lý quan hệ giữa các phần tử đầu vào"],
  ["fine-tuning", "AI/ML", "danh từ", "tiếp tục huấn luyện mô hình đã có bằng dữ liệu chuyên biệt cho một mục tiêu mới"],
  ["overfitting", "AI/ML", "danh từ", "tình trạng mô hình khớp quá sát dữ liệu huấn luyện và hoạt động kém trên dữ liệu mới"],
  ["underfitting", "AI/ML", "danh từ", "tình trạng mô hình chưa học đủ cấu trúc dữ liệu nên dự đoán kém cả trên dữ liệu huấn luyện"],
  [
    "precision",
    "AI/ML",
    "danh từ",
    "trong phân loại, tỷ lệ dự đoán dương tính là đúng trên tổng số dự đoán dương tính",
    undefined,
    false,
    ["classification", "positive prediction", "true positive", "precision-recall", "classifier metric"],
  ],
  [
    "precision",
    "AI/ML · Tính toán số",
    "danh từ",
    "độ chính xác số học hoặc độ phân giải của biểu diễn số, thường phụ thuộc vào số bit dùng cho mỗi giá trị",
    "Quantization reduces weight precision from 32-bit to 8-bit.",
    false,
    ["quantize", "quantization", "INT8", "bit precision", "weight precision", "32-bit", "8-bit"],
  ],
  [
    "recall",
    "AI/ML",
    "danh từ",
    "trong phân loại, tỷ lệ trường hợp dương tính thật được mô hình tìm thấy",
    undefined,
    false,
    ["classification", "positive cases", "true positive", "classifier metric", "precision-recall"],
  ],
  [
    "recall",
    "AI/ML",
    "danh từ",
    "khả năng truy xuất hoặc nhớ lại nội dung đã lưu trong bộ nhớ của hệ thống khi cần",
    "Fine-tuning can reduce the model's recall of previously stored content.",
    false,
    ["catastrophic forgetting", "old content", "memory", "previously stored", "knowledge recall", "retrieval"],
  ],
  ["large language model", "AI/ML", "cụm danh từ", "mô hình ngôn ngữ được huấn luyện trên lượng văn bản lớn để xử lý và tạo ngôn ngữ"],
  ["vector database", "AI/ML", "cụm danh từ", "cơ sở dữ liệu lưu vector và hỗ trợ tìm các vector gần nhau theo độ tương tự"],
  ["retrieval-augmented generation", "AI/ML", "cụm danh từ", "cách tạo câu trả lời bằng cách truy xuất tài liệu liên quan rồi đưa chúng vào ngữ cảnh mô hình"],
  ["RAG", "AI/ML", "viết tắt", "viết tắt của retrieval-augmented generation: sinh nội dung có bổ sung ngữ cảnh được truy xuất"],
];

const entries = new Map<string, { entry: TechnicalGlossaryEntry; contextHints: string[][] }>();
for (const [
  term,
  domain,
  partOfSpeech,
  meaning,
  example,
  includeGeneralSenses,
  contextHints,
] of ROWS) {
  const key = term.normalize("NFC").trim().toLocaleLowerCase("en");
  const sense: LocalDictionarySense = {
    meaning,
    partOfSpeech,
    subPartOfSpeech: null,
    example: example ?? null,
    domain,
  };
  const existing = entries.get(key);
  if (existing) {
    existing.entry.senses.push(sense);
    existing.contextHints.push([...(contextHints ?? [])]);
    if (includeGeneralSenses) existing.entry.includeGeneralSenses = true;
  } else {
    entries.set(key, {
      entry: {
        term,
        senses: [sense],
        pronunciations: [],
        includeGeneralSenses: includeGeneralSenses ?? false,
      },
      contextHints: [[...(contextHints ?? [])]],
    });
  }
}

export function lookupTechnicalGlossary(term: string, context = ""): TechnicalGlossaryEntry | null {
  const record = entries.get(term.normalize("NFC").trim().toLocaleLowerCase("en"));
  if (!record) return null;

  const normalizedContext = context.normalize("NFKC").toLocaleLowerCase("en");
  if (!normalizedContext) return record.entry;

  const ranked = record.entry.senses
    .map((sense, index) => ({
      sense,
      index,
      score:
        record.contextHints[index]?.reduce(
          (score, hint) => score + (normalizedContext.includes(hint) ? 1 : 0),
          0,
        ) ?? 0,
    }))
    .sort((left, right) => right.score - left.score || left.index - right.index);
  if (ranked[0]?.score === 0) return record.entry;

  return { ...record.entry, senses: ranked.map(({ sense }) => sense) };
}

export function listTechnicalGlossaryTerms(): string[] {
  return [...entries.values()].map(({ entry }) => entry.term);
}
